# Minimal configuration: parse standard syslog-style log lines.
#
# Matches lines like:
#   2024-01-15 09:30:00 INFO  Application started
#   2024-01-15 09:30:01 ERROR Connection refused

[atoms]
timestamp = "\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}"
level     = "INFO|WARN|ERROR|DEBUG"
message   = ".+"

[[items]]
name = "log_entry"
[[items.parts]]
atom = "timestamp"
[[items.parts]]
regex = " "
[[items.parts]]
atom = "level"
[[items.parts]]
regex = " +"
[[items.parts]]
atom = "message"
